version: "2"
services:
  app:
    container_name: sportsprofile
    image: sportsprofile:1.0.0
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:3.4
    ports:
      - "27017:27017"
    command: mongod --smallfiles